apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-web-deployment
  template:
    metadata:
      labels:
        app: my-web-deployment
    spec:
      containers:
      - name: my-web-deployment
        image: <name>.azurecr.io/my-web-deployment:v1
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "512mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            port: 8000
            path: /health
          initialDelaySeconds: 3
          periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: my-web-deployment
spec:
  selector:
    app: my-web-deployment
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer