apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-web-deployment
  template:
    metadata:
      labels:
        app: my-web-deployment
    spec:
---
apiVersion: v1
kind: Service
metadata:
  name: my-web-deployment
spec:
  selector:
    app: my-web-deployment
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer