apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-web-deployment
  template:
    metadata:
      labels:
        app: my-web-deployment
    spec:
